# Generated by Django 5.1.6 on 2025-03-07 02:56

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextEducationMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('republic_scientific_journal', 'republic_scientific_journal'), ('foreign_scientific_journal', 'foreign_scientific_journal'), ('republic_conference_journal', 'republic_conference_journal'), ('foreign_conference_journal', 'foreign_conference_journal')], max_length=255)),
                ('article_number', models.CharField(blank=True, max_length=255, null=True)),
                ('article_date', models.DateField(blank=True, null=True)),
                ('article_file', models.FileField(blank=True, null=True, upload_to=web.models.article_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('request_type', models.CharField(choices=[('bug', 'bug'), ('feature', 'feature'), ('help', 'help'), ('other', 'other')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('resolved', 'resolved'), ('closed', 'closed')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='help_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=web.models.certificate_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bachelor_major', models.CharField(blank=True, max_length=255, null=True)),
                ('bachelor_diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('bachelor_diploma_date', models.DateField(blank=True, null=True)),
                ('master_major', models.CharField(blank=True, max_length=255, null=True)),
                ('master_diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('master_diploma_date', models.DateField(blank=True, null=True)),
                ('next_education', models.CharField(blank=True, choices=[('intern', 'intern_researcher'), ('phd', 'phd'), ('dsc', 'dsc'), ('independent_phd', 'independent_phd'), ('independent_dsc', 'independent_dsc')], max_length=255, null=True)),
                ('next_education_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255)),
                ('teacher_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_academic_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_work_place_position', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edu_profile', to=settings.AUTH_USER_MODEL)),
                ('next_education_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_education_majors', to='web.nexteducationmajor')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, default='Profile\\_Default\\default.png', null=True, upload_to=web.models.profile_picture_path)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('living_place', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, validators=[web.models.PassportNumberValidator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('3-month', '3-month'), ('6-month', '6-month'), ('annual', 'annual'), ('other', 'other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('submitted', 'submitted'), ('under_review', 'under_review'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
