# Generated by Django 5.1.6 on 2025-03-07 02:59

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nexteducationmajor_article_helprequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=web.models.help_attachment_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=web.models.report_path),
        ),
    ]
