# Generated by Django 5.1.6 on 2025-03-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_helprequest_attachment_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprofile',
            name='next_education_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True),
        ),
    ]
