# Generated by Django 5.1.6 on 2025-03-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_educationprofile_next_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprofile',
            name='next_education_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_education_majors', to='web.nexteducationmajor'),
        ),
    ]
