# Generated by Django 5.1.6 on 2025-03-07 03:34

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_educationprofile_next_education_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation_title', models.CharField(max_length=500)),
                ('dissertation_progress', models.IntegerField(default=0)),
                ('dissertation_file', models.FileField(blank=True, null=True, upload_to=web.models.dissertation_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dissertation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
