# Generated by Django 5.1.6 on 2025-03-07 14:49

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_dissertation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[web.models.PassportNumberValidator]),
        ),
    ]
