# Generated by Django 5.1.6 on 2025-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_profile_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
