# Generated by Django 5.1.6 on 2025-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_profile_email_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexteducationmajor',
            name='number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
